name: Prod Deploy
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - prod

jobs:
  build:
    # Job name is Greeting
    name: Build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: build + deploy
          uses: actions/checkout@v1
          uses: JamesIves/github-pages-deploy-action@master
          env:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            BASE_BRANCH: master # The branch the action should deploy from.
            BRANCH: prod # The branch the action should deploy to.
            FOLDER: dist # The folder the action should deploy.
            BUILD_SCRIPT: npm install && npm run build # The build script the action should run prior to deploying.

      # - run: npm run build

      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'